name = "mikan"
main = "src/index.ts"
compatibility_date = "2025-01-17"
compatibility_flags = ["nodejs_compat"]

workers_dev = true
routes = [{ pattern = "mikan.liuyang-art.com", custom_domain = true }]

[vars]
UPSTREAM = "mikanani.me"

[placement]
mode = "smart"

[observability.logs]
enabled = true
