name = "mikan"
main = "src/index.ts"
compatibility_date = "2025-01-17"
compatibility_flags = ["nodejs_compat"]

[placement]
mode = "smart"

[env.production]
workers_dev = true
routes = [{ pattern = "mikan.siki.moe", custom_domain = true }]
[env.production.vars]
UPSTREAM = "mikanani.me"

[env.preview]
workers_dev = true
[env.preview.vars]
UPSTREAM = "mikanani.me"
